### ISSUE TITLE
Add Cell/Event Isolation

### ISSUE THREAD

**Issue by ronelm2000** [IceKirby/kirafan-timer#2]
[Suggestion]
Have some kind of way to isolate only a certain cell by using an query of some sort. The expected result would be something like this:
![image](https://user-images.githubusercontent.com/12634987/111967703-5294ab80-8b33-11eb-8d41-b5eb8304e600.png)

[Usage]
Display it as an OBS widget.

**Comment by IceKirby** [comment]
Sorry for the late reply, I'm so not used to getting feedback that I forgot to check for the issues here :x
I'll look into it, shouldn't be hard other than deciding how to define the ID.

**Comment by IceKirby** [comment]
Added parameters to the Readme, let me know if you need any other parameter.

**Comment by ronelm2000** [comment]
should be good for me, thnx for this, really appreciate it.
